version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: strapi-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build: ./apps/strapi
    container_name: strapi-app
    depends_on:
      - postgres
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development

  nest:
    build: ./apps/nestjs
    container_name: nest-api
    depends_on:
      - strapi
    ports:
      - "3001:3001"

  next:
    build: ./apps/nextjs
    container_name: next-frontend
    depends_on:
      - nest
    ports:
      - "3000:3000"

volumes:
  postgres_data:
